### ISSUE TITLE
The effects are not applied.  

### ISSUE THREAD

**Issue by AswinPG** [sswi/AcrylicView.MAUI#1]
Acrylic View is always rendered in Light Effect even if we give it dark, extra dark or anything else.

While I tried to troubleshoot I found that this line causes the execution of the `MapEffectStyle `method to return.

```
if (!float.TryParse(ver, out float version))
                return;
```
The `ver ` value I was getting was `16.4.1`  which cannot be parsed into a float..

**Comment by AswinPG** [comment]
https://github.com/sswi/AcrylicView.MAUI/pull/2

**Comment by sswi** [comment]
我也发现了这个问题，ExtraDark 仅在Tvos上支持，所以我将删除这个版本号判断。
谢谢你的反馈
<img width="488" alt="Snipaste_2023-05-17_18-34-51" src="https://github.com/sswi/AcrylicView.MAUI/assets/39110708/7bfd0e9c-43c7-4987-a854-165e13a895a0">

![QQ截图20230517183147](https://github.com/sswi/AcrylicView.MAUI/assets/39110708/ce9e49ae-0afa-4004-a55e-fbc3aa145808)

![QQ截图20230517183243](https://github.com/sswi/AcrylicView.MAUI/assets/39110708/79ed867e-b925-4534-8b68-8a02a65fe6d1)
