### ISSUE TITLE
Padding is not working on windows platform Windows platform 

### ISSUE THREAD

**Issue by Strypper** [sswi/AcrylicView.MAUI#7]
### Platform
Windows 

### Property 
Padding

### Version
.net version: `NET8` 
Nuget version: `2.1.0`

I notice that when I migrate to net 8 and use version `2.1.0` the padding is not working

**Comment by sswi** [comment]
This seems to be an issue with the NET8.0 MAUI framework. It was working fine in NET7.0, and I will continue to track this issue.

**Comment by sswi** [comment]
The issue has been temporarily resolved, please update the version to 2.1.1 ,Thanks
